### ISSUE TITLE
[Bug] Animation for Crystal Ball only plays every other click.

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/hacktoberfest#11]
Animations are triggered by toggling a class. This means that when you click once the class is toggled on or off, requiring two clicks to restart the animations. 

Looking for a way to remove the animation class at the end of the animation loop or another method to ensure the animation starts on every click.

https://github.com/CircleCI-Public/hacktoberfest/blob/master/src/components/CrystalBall.vue#L27

**Comment by frunkad** [comment]
Can I take this up?

**Comment by KyleTryon** [comment]
@frunkad it appears as if a pr #14 has been submitted.
