### ISSUE TITLE
The Website Isn't Versioned

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/hacktoberfest#7]
The site isn't versioned at all. Aside from the copyright statement, "2019" or something like "Orbtoberfest 1" doesn't appear anywhere on the site.

**Comment by markstonehouse** [comment]
Submitted a PR #18 adding the year '2019' to any references to Orbtoberfest on the website. Only added the year where it seemed appropriate.

**Comment by KyleTryon** [comment]
@felicianotech This will have to be brought up with our marketing team. As far as I am aware while we may continue to participate in hacktoberfest, next year could possibly not be orb themed. I still agree with adding a copyright. 

2019 is not mentioned on the official digital ocean site either except for in the footer: https://hacktoberfest.digitalocean.com/

**Comment by markstonehouse** [comment]
> @felicianotech This will have to be brought up with our marketing team. As far as I am aware while we may continue to participate in hacktoberfest, next year could possibly not be orb themed. I still agree with adding a copyright.
> 
> 2019 is not mentioned on the official digital ocean site either except for in the footer: https://hacktoberfest.digitalocean.com/

That's a fair point. The actual logo for digital ocean website has the year in it too, but that itself does change each year.
